"""one open visit per user

Revision ID: 9da6bc62edac
Revises: a6c262864b48
Create Date: 2026-07-27 23:10:50.334607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9da6bc62edac'
down_revision: Union[str, None] = 'a6c262864b48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uq_visits_one_open_per_user', 'visits', ['user_id'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_visits_one_open_per_user', table_name='visits', postgresql_where=sa.text('ended_at IS NULL'))
    # ### end Alembic commands ###
