"""initial schema

Revision ID: a6c262864b48
Revises: 
Create Date: 2026-07-27 23:03:06.171554

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a6c262864b48'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('menu_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('sized', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('in_catalog', sa.Boolean(), nullable=False),
    sa.CheckConstraint("(category = 'drink') = sized", name='ck_menu_items_only_drinks_are_sized'),
    sa.CheckConstraint("category IN ('drink', 'food')", name='ck_menu_items_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id', 'sized', name='uq_menu_items_id_sized'),
    sa.UniqueConstraint('name')
    )
    op.create_table('size_modifiers',
    sa.Column('size', sa.String(length=10), nullable=False),
    sa.Column('delta_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint("size IN ('small', 'medium', 'large')", name='ck_size_modifiers_size'),
    sa.PrimaryKeyConstraint('size')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('name_key', sa.String(length=40), nullable=False),
    sa.Column('current_day', sa.Integer(), nullable=False),
    sa.Column('wallet_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_name_key'), 'users', ['name_key'], unique=True)
    op.create_table('customer_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('visits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_name', sa.String(length=40), nullable=True),
    sa.Column('inserted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('user', 'barista', 'tool')", name='ck_messages_role'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('placed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visit_menu_items',
    sa.Column('visit_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['visit_id'], ['visits.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('visit_id', 'menu_item_id')
    )
    op.create_table('cart_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cart_id', sa.Integer(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('sized', sa.Boolean(), nullable=False),
    sa.CheckConstraint("size IS NULL OR size IN ('small', 'medium', 'large')", name='ck_cart_lines_size_value'),
    sa.CheckConstraint('sized = (size IS NOT NULL)', name='ck_cart_lines_size_matches_item'),
    sa.ForeignKeyConstraint(['cart_id'], ['carts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['menu_item_id', 'sized'], ['menu_items.id', 'menu_items.sized'], name='fk_cart_lines_item_sized'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cart_id', 'menu_item_id', 'size', name='uq_cart_lines_item_size')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('menu_item_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('size', sa.String(length=10), nullable=True),
    sa.Column('sized', sa.Boolean(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.CheckConstraint("size IS NULL OR size IN ('small', 'medium', 'large')", name='ck_order_lines_size_value'),
    sa.CheckConstraint('sized = (size IS NOT NULL)', name='ck_order_lines_size_matches_item'),
    sa.ForeignKeyConstraint(['menu_item_id', 'sized'], ['menu_items.id', 'menu_items.sized'], name='fk_order_lines_item_sized'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_lines')
    op.drop_table('cart_lines')
    op.drop_table('visit_menu_items')
    op.drop_table('orders')
    op.drop_table('messages')
    op.drop_table('carts')
    op.drop_table('visits')
    op.drop_table('customer_preferences')
    op.drop_index(op.f('ix_users_name_key'), table_name='users')
    op.drop_table('users')
    op.drop_table('size_modifiers')
    op.drop_table('menu_items')
    # ### end Alembic commands ###
