"""order idempotency key

Revision ID: f57fc07f5887
Revises: 9da6bc62edac
Create Date: 2026-07-28 16:16:44.504225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f57fc07f5887'
down_revision: Union[str, None] = '9da6bc62edac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('cart_version', sa.Integer(), nullable=False))
    op.create_unique_constraint('uq_orders_visit_cart_version', 'orders', ['visit_id', 'cart_version'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_orders_visit_cart_version', 'orders', type_='unique')
    op.drop_column('orders', 'cart_version')
    # ### end Alembic commands ###
